POST http://localhost:8880/ebook/list
Accept: application/json

###



POST http://localhost:8880/ebook/page
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "mysql",
  "pageNum": 1,
  "pageSize": 10
}

###


